[env]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600
board_build.partitions = huge_app.csv
lib_deps =
    sparkfun/SparkFun Qwiic 6Dof - LSM6DSO@^1.0.3

[env:partA]
build_src_filter = +<partA_ble_led.cpp>

[env:partB]
build_src_filter = +<partB_step_counter.cpp>
